# Generated by Django 2.1.5 on 2019-01-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190125_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['module']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['course']},
        ),
    ]
